[WIP] Updated `quick-install` script.
- Added "x failed operations" prompt where there are things that failed.
- Added rofi dotfiles installation.

NOTE: This script will have at least 1 failed operation for now because
I haven't pushed the WIP rofi dotfiles yet.

Signed-off-by: Chris1320 <chris1320is@protonmail.com>

diff --git a/quick-install b/quick-install
--- a/quick-install
+++ b/quick-install
@@ -11,6 +11,8 @@ SCRIPTS_PATH="$PWD/scripts"
 SCRIPTS_DST_PATH="$HOME/.config/scripts"
 PROMPT_CONFIRMATION_TIMEOUT=30  # timeout in seconds
 
+failed_operations_num=0
+
 # Create the directory if it does not exist.
 #
 # :param $1: The directory name
@@ -62,7 +64,10 @@ simpleDotfileInstall() {
         fi
         if ! cp "$src_path" "$dst_path"; then
             echo "[!] ${color_warning}Retrying copy with sudo...${style_reset}"
-            sudo cp "$src_path" "$dst_path"
+            if ! sudo cp "$src_path" "$dst_path"; then
+                echo "[E] ${color_error} Failed to copy $name dotfiles.${style_reset}"
+                declare -g failed_operations_num=$((failed_operations_num + 1))
+            fi
         fi
 
     else
@@ -73,7 +78,10 @@ simpleDotfileInstall() {
         checkDir "$(dirname "$dst_path")"
         if ! cp -r "$src_path" "$dst_path"; then
             echo "[!] ${color_warning}Retrying copy with sudo...${style_reset}"
-            sudo cp -r "$src_path" "$dst_path"
+            if ! sudo cp -r "$src_path" "$dst_path"; then
+                echo "[E] ${color_error} Failed to copy $name dotfiles.${style_reset}"
+                declare -g failed_operations_num=$((failed_operations_num + 1))
+            fi
         fi
     fi
 }
@@ -94,6 +102,8 @@ main() {
     # NOTE: do not delete mpd's directory; it contains the database and other user data
     simpleDotfileInstall "mpd" "$DOTFILES_PATH/mpd/mpd.conf" "$HOME/.config/mpd/mpd.conf"
     simpleDotfileInstall "ncmpcpp" "$DOTFILES_PATH/ncmpcpp/config" "$HOME/.config/ncmpcpp/config"
+    simpleDotfileInstall "rofi (.config)" "$DOTFILES_PATH/rofi/config/config.rasi" "$HOME/.config/rofi/config.rasi"
+    simpleDotfileInstall "rofi (.local)" "$DOTFILES_PATH/rofi/local/catppuccin-mocha.rasi" "$HOME/.local/share/rofi/themes/catppuccin-mocha.rasi"
     simpleDotfileInstall "SDDM" "$DOTFILES_PATH/sddm/sddm.conf" "/etc/sddm.conf.d/sddm.conf"
     simpleDotfileInstall "swappy" "$DOTFILES_PATH/swappy/config" "$HOME/.config/swappy/config"
     simpleDotfileInstall "swaylock" "$DOTFILES_PATH/swaylock/config" "$HOME/.config/swaylock/config"
@@ -110,10 +120,20 @@ main() {
         printf "\tRemoving existing %s directory...\n" "$SCRIPTS_DST_PATH"
         rm -r "$SCRIPTS_DST_PATH"
     fi
-    cp -r "$SCRIPTS_PATH" "$SCRIPTS_DST_PATH"
-    echo "[i] ${color_info}Copying scripts... Done!${style_reset}"
+    if cp -r "$SCRIPTS_PATH" "$SCRIPTS_DST_PATH"; then
+        echo "[i] ${color_info}Copying scripts... Done!${style_reset}"
+    else
+        echo "[E] ${color_error} Failed to copy scripts.${style_reset}"
+        declare -g failed_operations_num=$((failed_operations_num + 1))
+    fi
 
-    exit 0
+    if [[ $failed_operations_num -eq 1 ]]; then
+        echo "[!] ${color_warning}There was ${color_error}1${color_warning} failed operation.${style_reset}"
+    elif [[ $failed_operations_num -gt 1 ]]; then
+        echo "[!] ${color_warning}There were ${color_error}$failed_operations_num${color_warning} failed operations.${style_reset}"
+    fi
+
+    exit $failed_operations_num
 }
 
 main
